# Generated by Django 4.2.1 on 2023-08-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0002_homephoto_delete_homepic_chapters_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('Chname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.chapters')),
            ],
        ),
    ]
