# Generated by Django 4.2.1 on 2023-08-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0003_videophoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(default='', upload_to='images')),
                ('subname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectpolls.subject')),
            ],
        ),
    ]
