# Generated by Django 4.2.1 on 2023-08-17 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0005_usertestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('chplect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.chapters')),
            ],
        ),
    ]
