# Generated by Django 4.2.1 on 2023-08-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0008_class_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='pdf_img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
