# Generated by Django 4.2.1 on 2023-09-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0010_question_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='QChp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('subtopic', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Que',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('correct_ans', models.CharField(max_length=100)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.qchp')),
            ],
        ),
        migrations.AlterField(
            model_name='option',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.que'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
