# Generated by Django 4.2.1 on 2023-09-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0012_videos_delete_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathsVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video_url', models.CharField(max_length=300)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.subject')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='ChemVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video_url', models.CharField(max_length=300)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.subject')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='BioVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('video_url', models.CharField(max_length=300)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.subject')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.chapters')),
            ],
        ),
    ]
