# Generated by Django 4.2.1 on 2023-09-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0013_mathsvideos_chemvideos_biovideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
