# Generated by Django 4.2.1 on 2023-09-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0016_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='rahul07@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='Pass',
            field=models.CharField(default='rahul', max_length=100),
        ),
    ]
