# Generated by Django 4.2.1 on 2023-09-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0017_alter_user_email_alter_user_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Pass',
            field=models.CharField(default='', max_length=100),
        ),
    ]
