# Generated by Django 4.2.1 on 2023-09-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0018_alter_user_email_alter_user_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastAccessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed_video_url', models.CharField(max_length=300)),
                ('last_accessed_video_title', models.CharField(max_length=255)),
                ('last_accessed_video_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.user')),
            ],
        ),
    ]
