# Generated by Django 4.2.1 on 2023-09-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0021_alter_lastaccessedvideo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_attended', models.PositiveIntegerField(default=0)),
                ('total_minutes_watched', models.PositiveIntegerField(default=0)),
                ('total_quizzes_attended', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectpolls.user')),
            ],
        ),
    ]
