# Generated by Django 4.2.1 on 2023-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0022_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_minutes_watched',
            field=models.IntegerField(default=0),
        ),
    ]
