# Generated by Django 4.2.1 on 2023-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0023_alter_userprofile_total_minutes_watched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('pdf_img', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
