# Generated by Django 4.2.1 on 2023-10-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0024_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='biovideos',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
