# Generated by Django 4.2.1 on 2023-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpolls', '0025_biovideos_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Num',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
